apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: my-app
    app.kubernetes.io/name: node-frontend
  name: frontend-deployment
  namespace: node-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-app
      tier: node-frontend
  template:
    metadata:
      labels:
        app: my-app
        tier: node-frontend
    spec:
      containers:
        - image: rajputvikram/frontend:latest
          resources:
            requests:
              cpu: 500m
              memory: 600Mi
          name: node-app-frontend
          ports:
            - containerPort: 5000
          env:
          - name: backend
            value: backend:8000
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: node-frontend
  name: frontend
  namespace: node-app
spec:
  selector:
    app: my-app
    tier: node-frontend
  ports:
   -  protocol: TCP
      port: 5000
      targetPort: 5000
  type: LoadBalancer    
